#include "libft.h"
#include "couleurs.h"

int     main(void)
{
	clrscr();
	couleur("31");
	printf("\n\t    SIMPLE TESTS FOR LIBFT");
	couleur("35");
	printf ("\n\n      Expected output : "); 
	couleur("32");
	printf ("User output\n\n\n ");
	couleur("0");

//	sleep(2);
	couleur("36");
	printf("\t\t___FT_ATOI___\n");
	couleur("35");
	printf("\t\t    0 : ");
	couleur("32");
	printf("%d\n", ft_atoi("0"));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n", ft_atoi("1"));
	couleur("35");
	printf("\t\t   -5 : ");
	couleur("32");
	printf("%d\n", ft_atoi("-5"));
	couleur("35");
	printf("\t\t   42 : ");
	couleur("32");
	printf("%d\n", ft_atoi("42"));
	couleur("35");
	printf("\t\t  -42 : ");
	couleur("32");
	printf("%d\n", ft_atoi("-42"));
	couleur("35");
	printf("\t       876568 : ");
	couleur("32");
	printf("%d\n", ft_atoi("876568"));
	couleur("35");
	printf("\t       -48965 : ");
	couleur("32");
	printf("%d\n", ft_atoi("-48965"));
	couleur("35");
	printf("\t  -2147483648 : ");
	couleur("32");
	printf("%d\n", ft_atoi("2147483648"));
	couleur("35");
	printf("\t   2147483647 : ");
	couleur("32");
	printf("%d\n", ft_atoi("2147483647"));
	couleur("35");
	printf("\t  -2147483648 : ");
	couleur("32");
	printf("%d\n", ft_atoi("-2147483648"));
	couleur("35");
	printf("\t    123456000 : ");
	couleur("32");
	printf("%d\n", ft_atoi("123456000"));
	printf("\n\n");
//	sleep(1);
	//////////////////
	couleur("36");
	printf("\t\t___FT_ITOA___\n");
	couleur("35");
	printf("\t\t    0 : ");
	couleur("32");
	printf("%s\n", ft_itoa(0));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%s\n", ft_itoa(1));
	couleur("35");
	printf("\t\t   -5 : ");
	couleur("32");
	printf("%s\n", ft_itoa(-5));
	couleur("35");
	printf("\t\t   42 : ");
	couleur("32");
	printf("%s\n", ft_itoa(42));
	couleur("35");
	printf("\t\t  -42 : ");
	couleur("32");
	printf("%s\n", ft_itoa(-42));
	couleur("35");
	printf("\t\t 1567 : ");
	couleur("32");
	printf("%s\n", ft_itoa(1567));
	couleur("35");
	printf("\t\t-6654 : ");
	couleur("32");
	printf("%s\n", ft_itoa(-6654));
	couleur("35");
	printf("\t  -2147483648 : ");
	couleur("32");
	printf("%s\n", ft_itoa(2147483648));
	couleur("35");
	printf("\t   2147483647 : ");
	couleur("32");
	printf("%s\n", ft_itoa(2147483647));
	couleur("35");
	printf("\t  -2147483648 : ");
	couleur("32");
	printf("%s\n", ft_itoa(-2147483648));
	couleur("35");
	printf("\t    123456000 : ");
	couleur("32");
	printf("%s\n\n\n", ft_itoa(123456000));
//	sleep(1);
	////////////////////////
	couleur("36");
	printf("\t\t___FT_IS?___\n");
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n", ft_isascii(27));
	couleur("35");
	printf("\t\t    0 : ");
	couleur("32");
	printf("%d\n", ft_isalpha(27));
	couleur("35");
	printf("\t\t    0 : ");
	couleur("32");
	printf("%d\n", ft_isalpha(48));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n", ft_isprint(92));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n", ft_isalpha(100));
	couleur("35");
	printf("\t\t    0 : ");
	couleur("32");
	printf("%d\n", ft_isdigit(59));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n", ft_isdigit(53));
	couleur("35");
	printf("\t\t    0 : ");
	couleur("32");
	printf("%d\n", ft_isascii(3546));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n", ft_isascii(0));
	couleur("35");
	printf("\t\t    1 : ");
	couleur("32");
	printf("%d\n\n", ft_isalnum(76));
//	sleep(1);
	/////////////////////////
	couleur("36");
	printf("\t\t___FT_STRCHR___\n");
	couleur("33");
	printf("Reference sentence : Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port\n");
	couleur("32");
	printf("%s\n", ft_strchr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", 116));
	couleur("35");
	printf("%s\n", strchr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", 116));
	couleur("31");
	printf("diff = %d\n\n", (ft_strcmp((ft_strchr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", 116)), strchr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", 116))));
	couleur("33");
	printf("Reference sentence : Je déteste les animaux préhistoriques partouzeurs de droite, bordel !\n");
	couleur("32");
	printf("%s\n", ft_strchr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", 97));
	couleur("35");
	printf("%s\n", strchr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", 97));
	couleur("31");
	printf("diff = %d\n\n", (ft_strcmp((ft_strchr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", 97)), strchr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", 97))));
//	sleep(1);
	//////////////////////////
	couleur("36");
	printf("\t\t___FT_STRSTR___\n");
	couleur("33");
	printf("Reference sentence : Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port\n");
	couleur("32");
	printf("%s\n", (ft_strstr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", "mais par")));
	couleur("35");
	printf("%s\n", strstr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", "mais par"));
	couleur("31");
	printf("diff = %d\n\n", (ft_strcmp((ft_strstr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", "mais par")), strstr("Nous partîmes 500 mais par un prompt renfort nous nous vîmes 3000 en arrivant au port", "mais par"))));
	couleur("33");
	printf("Reference sentence : Je déteste les animaux préhistoriques partouzeurs de droite, bordel !\n");
	couleur("32");
	printf("%s\n", ft_strstr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", "este les an"));
	couleur ("35");
	printf("%s\n", strstr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", "este les an"));
	couleur("31");	
	printf("diff = %d\n\n", (ft_strcmp((ft_strstr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", "este les an")), strstr("Je déteste les animaux préhistoriques partouzeurs de droite, bordel !", "este les an"))));
//	sleep(1);
	///////////////////////
	couleur("36");
	printf("\t\t___FT_STRCMP___\n");
	couleur("35");
	printf("\t\t    %d : ", strcmp("Il etait une fois dans une galaxie lointaine, tres lointaine", "Il etait une fois dans une galaxie lointaine, tres lointaine"));
	couleur("32");
	printf("%d\n", ft_strcmp("Il etait une fois dans une galaxie lointaine, tres lointaine", "Il etait une fois dans une galaxie lointaine, tres lointaine"));
	couleur("35");
	printf("\t\t   %d : ", strcmp("Il etait une fois dans une galaxie lointaine, tres lointaine", "Il etait une fois dans une galaxie lointaine tres lointaine"));
	couleur("32");
	printf("%d\n", ft_strcmp("Il etait une fois dans une galaxie lointaine, tres lointaine", "Il etait une fois dans une galaxie lointaine, tres lointaine"));
	couleur("35");
	printf("\t\t   %d : ", strcmp("Il etait une fois dans une galaxie lointaine, tres lointaine", "Il etait une fois dans une galaxie lointaine."));
	couleur("32");
	printf("%d\n", ft_strcmp("Il etait une fois dans une galaxie lointaine, tres lointaine", "Il etait une fois dans une galaxie lointaine."));
	couleur("35");
	printf("\t\t  %d : ", strcmp("\200", "\0"));
	couleur("32");
	printf("%d\n", ft_strcmp("\200", "\0"));
	couleur("35");
	printf("\t\t  %d : ", strcmp("\0", "Bonjour"));
	couleur("32");
	printf("%d\n\n", ft_strcmp("\0", "Bonjour"));
	////////////////////////
	couleur("36");
	printf("\t\t___FT_STRJOIN___\n");
	couleur("32");
	printf("%s\n", ft_strjoin("Il etait une fois, ", "dans une galaxie lointaine"));
	printf("%s\n", ft_strjoin("....\n..##\n", "..##\n...."));
	printf("%s\n\n", ft_strjoin("42 c'est quand meme une ", "école vraiment cool"));
	/////////////////////////
	couleur("36");
	printf("\t\t___FT_STRSPLIT___\n");
	couleur("32");
	char *s = "TCFRDFCT1PPPPPPPP1BBBBBBBB1BBBBBBBB1BBBBBBBB1BBBBBBBB1PPPPPPPP1TCFRDFCT1";
	char **tbl = ft_strsplit(s, '1');
	while (*tbl)
	{
		printf("%s\n", *tbl);
		tbl++;
	}

	return (0);
}
